### ISSUE TITLE
错误处理应该判断类型

### ISSUE THREAD

**Issue by berwin** [thinkjs/think-trace#1]
比如我用浏览器访问server报错应该返回html格式，但如果我用 ajax 请求server报错了还返回html格式就不对了、、

@lizheming

**Comment by lizheming** [comment]
thinkjs2 原来的逻辑就是这样的，而且也不太好确认你是 ajax 请求啊，也不是所有的 ajax 请求都有自定义头。

**Comment by berwin** [comment]
可以通过 Accept 来判断请求类型，我记得koa内置就有一个方法来判断类型的 `ctx.accepts` 这个方法

**Comment by lizheming** [comment]
accepts 判断多麻烦.... json 和 xml, image 都得去判断...而且 json 的 stack 的堆栈返回出来多不友好。

**Comment by berwin** [comment]
我看只判断 html 和 json 就行，最多在加一个 text 就是对这三种情况分别做个简单处理就好。就是html的就返回现在这样的，json的就返回 {error: err.message}，text就直接返回一个err.message。

**Comment by lizheming** [comment]
好

**Comment by berwin** [comment]
😊😊😊

**Comment by lizheming** [comment]
v1.0.9 supported!
