### ISSUE TITLE
json 错误不正确

### ISSUE THREAD

**Issue by huanz** [thinkjs/think-trace#3]
[L114](https://github.com/thinkjs/think-trace/blob/master/lib/tracer.js#L114)

这里的判断返回的都是 null ，thinkjs：3.0.0-beta4

**Comment by lizheming** [comment]
对，现在有点问题，我们看看怎么弄改一下。

**Comment by lizheming** [comment]
添加了 contentType 参数用来自定义设置报错头的 content type，具体用法可查看 README。
fixed at https://github.com/thinkjs/think-trace/commit/9e2c73dea4604aefa930c54c2e355d66e08dbb99

**Comment by huanz** [comment]
config里面有个jsonContentType拿不到么？
            在2017年08月14日 18:23，公子 写道： 添加了 contentType 参数用来自定义设置报错头的 content type，具体用法可查看 README。
fixed at 9e2c73d

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/thinkjs/think-trace","title":"thinkjs/think-trace","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/thinkjs/think-trace"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lizheming in #3: 添加了 contentType 参数用来自定义设置报错头的 content type，具体用法可查看 README。\r\nfixed at https://github.com/thinkjs/think-trace/commit/9e2c73dea4604aefa930c54c2e355d66e08dbb99"}],"action":{"name":"View Issue","url":"https://github.com/thinkjs/think-trace/issues/3#issuecomment-322155010"}}}

**Comment by lizheming** [comment]
`jsonContentType` 这个参数是用来指定 `json` 输出时的 `content-type` 的，并不能代表当前请求是 JSON 格式输出，因为一个项目不是所有的输出都是 JSON 的。
