### ISSUE TITLE
[BUG] wrong http status

### ISSUE THREAD

**Issue by dsonet** [thinkjs/think-trace#4]
whatever the error is, HTTP status always return 200 which should return corresponding error status.

My current solution is add the following code in tracer.js->run(cxt, err) 

`ctx.status = err.status;`

**Comment by lizheming** [comment]
fixed at https://github.com/thinkjs/think-trace/commit/a16c33f534188036fac91ae2de17fa93daa40744

**Comment by dsonet** [comment]
Added commnet at 
https://github.com/thinkjs/think-trace/blob/a16c33f534188036fac91ae2de17fa93daa40744/lib/index.js#L36

**Comment by lizheming** [comment]
NO, that's correct code, you can test it.

**Comment by dsonet** [comment]
Ya you are right, it works.

**Comment by lizheming** [comment]
OK. In fact, `err.status` will equal with `ctx.status` in that case.

**Comment by dsonet** [comment]
@lizheming It's actually not. It's only works when throw(404), but not any other status.
I tried with 401, it doesn't work correctly. the ctx.status is 404, the err.status is correct as 401.
So I think it should use err.status instead.

**Comment by lizheming** [comment]
yes, you are right, I miss understand some code.
